# Generated by Django 5.1.4 on 2025-02-12 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameChildPostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Должности для отделений',
                'verbose_name_plural': 'Должности для отделений',
            },
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.RenameField(
            model_name='rolemodel',
            old_name='name_role',
            new_name='name',
        ),
        migrations.AddField(
            model_name='workaroundmodel',
            name='date_of_update',
            field=models.TimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='signaturemodel',
            name='pk_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ключ пользователя'),
        ),
        migrations.AlterField(
            model_name='signaturemodel',
            name='wasm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.workaroundsheetmodel', verbose_name='Пункт обходного листа'),
        ),
        migrations.AlterField(
            model_name='workaroundmodel',
            name='date_of_create',
            field=models.TimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='workaroundmodel',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.statusmodel', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='workaroundsheetmodel',
            name='decription',
            field=models.TextField(null=True, verbose_name='Описание пункта'),
        ),
        migrations.CreateModel(
            name='PostChildModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.namechildpostmodel', verbose_name='Должность в отделении')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.departmentmodel', verbose_name='Отделение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Должность в отделении',
                'verbose_name_plural': 'Должность в отделении',
            },
        ),
        migrations.AlterField(
            model_name='workaroundsheetmodel',
            name='depart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.postchildmodel', verbose_name='Роль человека который должен подписать'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.postmodel', verbose_name='Должность'),
        ),
    ]
