# Generated by Django 5.1.4 on 2025-02-12 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_namechildpostmodel_postmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='depart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.namechildpostmodel', verbose_name='Отделение'),
        ),
    ]
