# Generated by Django 5.1.4 on 2025-02-12 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customuser_depart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signaturemodel',
            old_name='pk_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='workaroundmodel',
            old_name='pk_user',
            new_name='user',
        ),
    ]
