# Generated by Django 5.1.4 on 2025-02-12 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_pk_user_signaturemodel_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='depart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.departmentmodel', verbose_name='Отделение'),
        ),
        migrations.AlterField(
            model_name='signaturemodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ключ пользователя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workaroundsheetmodel',
            name='decription',
            field=models.TextField(default=1, verbose_name='Описание пункта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workaroundsheetmodel',
            name='depart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.postmodel', verbose_name='Роль человека который должен подписать'),
        ),
    ]
