# Generated by Django 5.1.4 on 2025-02-12 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_customuser_depart_alter_signaturemodel_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workaroundsheetmodel',
            name='depart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.namechildpostmodel', verbose_name='Роль человека который должен подписать'),
        ),
    ]
