# Generated by Django 5.1.4 on 2025-02-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_workaroundsheetmodel_depart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workaroundsheetmodel',
            name='decription',
            field=models.TextField(null=True, verbose_name='Описание пункта'),
        ),
    ]
