# Generated by Django 5.1.4 on 2025-02-12 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_workaroundsheetmodel_decription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signaturemodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ключ пользователя'),
        ),
    ]
