# Generated by Django 5.1.4 on 2025-02-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_signaturemodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='workaroundsheetmodel',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок подписания'),
        ),
    ]
