# Generated by Django 5.1.6 on 2025-02-19 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_workaroundsheetmodel_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='depart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.departmentmodel', verbose_name='Отделение'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.rolemodel', verbose_name='Роль'),
        ),
    ]
