# Generated by Django 5.1.4 on 2025-02-26 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_customuser_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='typWorkAround',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название типа')),
            ],
        ),
        migrations.AddField(
            model_name='workaroundsheetmodel',
            name='is_required',
            field=models.BooleanField(default=True, verbose_name='Обязательный этап'),
        ),
        migrations.AddField(
            model_name='workaroundsheetmodel',
            name='workaround',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.workaroundmodel', verbose_name='Обходной лист'),
        ),
        migrations.AlterField(
            model_name='workaroundsheetmodel',
            name='depart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.namechildpostmodel', verbose_name='Должность для подписи'),
        ),
        migrations.AddField(
            model_name='workaroundmodel',
            name='typ',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.typworkaround'),
            preserve_default=False,
        ),
    ]
