# Generated by Django 5.1.4 on 2025-02-26 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_typworkaround_workaroundsheetmodel_is_required_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workaroundsheetmodel',
            options={'ordering': ['order'], 'verbose_name': 'Пункты обходного листа', 'verbose_name_plural': 'Пункты обходного листа'},
        ),
        migrations.AlterUniqueTogether(
            name='workaroundsheetmodel',
            unique_together={('workaround', 'order')},
        ),
    ]
