# Generated by Django 5.2 on 2025-05-24 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_workaroundsheetmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='namechildpostmodel',
            name='type_for_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.typworkaround'),
            preserve_default=False,
        ),
    ]
